global:
  scrape_interval: 30s
  evaluation_interval: 30s

  external_labels:
    monitor: 'prometheus-instigator'

rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'kafka_exporter'
    dns_sd_configs:
    - names:
      - 'tasks.kafka_exporter'
      type: 'A'
      port: 9308

  - job_name: 'kafka'
    static_configs:
    - targets:
      - broker1:7072
      - broker1:7072
      - broker1:7072
