global:
  scrape_interval: 30s
  evaluation_interval: 30s

  external_labels:
    monitor: 'prometheus-instigator'

rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - prometheus:9090

  - job_name: 'kafka_exporter'
    static_configs:
    - targets:
      - kafka_exporter:9308

  - job_name: 'kafka_jmx_exporter'
    static_configs:
    - targets:
      - instigator_broker_1:7072
      - instigator_broker_2:7072
      - instigator_broker_3:7072
